CREATE DATABASE Filmes;
GO

USE Filmes;
GO

CREATE TABLE Genero(
	IdGenero INT PRIMARY KEY IDENTITY,
	NomeGenero VARCHAR(200) NOT NULL
);
GO

CREATE TABLE Filme(
	IdFilme INT PRIMARY KEY IDENTITY,
	NomeFilme VARCHAR(200) NOT NULL,
	DataLancamento DATE NOT NULL,
	Diretor VARCHAR(200) NOT NULL,
	IdGenero INT FOREIGN KEY REFERENCES Genero(IdGenero)
);
GO

CREATE TABLE TipoUsuario(
IdTipoUsuario INT PRIMARY KEY IDENTITY,
NomeTipoUsuario VARCHAR(100)NOT NULL UNIQUE
);

CREATE TABLE Usuario(
	IdUsuario INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(200) NOT NULL,
	Email VARCHAR(200) NOT NULL,
	Senha VARCHAR(200) NOT NULL,
	IdTipoUsuario INT FOREIGN KEY REFERENCES TipoUsuario(idTipoUsuario)NOT NULL,
);
GO